-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

myFibs = 0 : 1 : next myFibs
       where
         next (a : t@(b:_)) = (a+b) : next t

fib = take 100 $ drop 2 myFibs  -- drop 2 to get same format as question (100 is well over 4mill)

evenFib = [x | x <- fib, x < 4000000, (x `mod` 2) == 0]

ans = sum evenFib
